version: '3.8'

networks:
  app-tier:
    driver: bridge

services:
  application:
    volumes:
      - ${PWD}/app:/app/app
      - ${PWD}/bin:/app/bin
      - ${PWD}/dev:/app/dev
      - ${PWD}/lib:/app/lib
      - ${PWD}/pub:/app/pub
      - ${PWD}/setup:/app/setup
      - ${PWD}/var:/app/var
      - ${PWD}/auth.json:/app/auth.json
      - ${PWD}/composer.json:/app/composer.json
      - ${PWD}/composer.lock:/app/composer.lock
      - ~/.composer:/var/www/.composer
      - ./application/vhosts/application.docker.conf:/opt/docker/etc/httpd/conf.d/application.docker.conf:cached
      - ./application/build/configuration/docker-php-ext-mailhog.ini:/usr/local/etc/php/conf.d/docker-php-ext-mailhog.ini:cached